apiVersion: v1
kind: Secret
metadata:
  name: node-postgres-redis-secrets
  labels:
    app.kubernetes.io/name: node-postgres-redis
type: Opaque
stringData:
  DATABASE_URL: ""
  REDIS_URL: ""
  S3_BUCKET: ""
