apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-spring-redis
  labels:
    app.kubernetes.io/name: java-spring-redis
spec:
  rules:
    - host: REPLACE_ME_HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-spring-redis
                port:
                  number: 8080
